### ISSUE TITLE
io.github.karlatemp.mxlib.selenium.WindowsKit 使用Logger输出信息

### ISSUE THREAD

**Issue by cssxsh** [Karlatemp/MxLib#1]
https://github.com/Karlatemp/MxLib/blob/cd827c86f5aa0955a3de893057f42f6ef0a0332d/mxlib.selenium/src/main/java/io/github/karlatemp/mxlib/selenium/WindowsKit.java#L49-L52

**Comment by Karlatemp** [comment]
这是 debug 信息（懒得删

**Comment by cssxsh** [comment]
> 这是 debug 信息（懒得删

System.out.println 会污染 std.out

我打算用你这里现成的轮子 截网页的图

话说有关闭 selenium 日志输出的方法吗，ProtocolHandshake 之类的好烦啊

**Comment by Karlatemp** [comment]
System.err 和 java.util.logging.Logger 应该就这两个
